
version: '2'

services:
  phreshr.react:
    image: phreshr.react:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080